/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

let _deepseek_ai_dsh_api_customizations_controller_customizations_addMcpServer_parameter_0$schema$value
const _deepseek_ai_dsh_api_customizations_controller_customizations_addMcpServer_parameter_0$schema = () => (_deepseek_ai_dsh_api_customizations_controller_customizations_addMcpServer_parameter_0$schema$value ??= z.object({
  'id': z.string().readonly(),
  'serverName': z.string().readonly(),
  'transport': z.union([z.literal("stdio"), z.literal("streamable-http")]).readonly(),
  'command': z.string().readonly().optional(),
  'args': z.array(z.string()).readonly().optional(),
  'env': z.record(z.string(), z.string()).readonly().readonly().optional(),
  'cwd': z.string().readonly().optional(),
  'url': z.string().readonly().optional(),
  'headers': z.record(z.string(), z.string()).readonly().readonly().optional(),
  'enabled': z.boolean().readonly(),
}))
let _deepseek_ai_dsh_api_customizations_controller_customizations_addMcpServer_result$schema$value
const _deepseek_ai_dsh_api_customizations_controller_customizations_addMcpServer_result$schema = () => (_deepseek_ai_dsh_api_customizations_controller_customizations_addMcpServer_result$schema$value ??= z.void())
let _deepseek_ai_dsh_api_customizations_controller_customizations_balance_result$schema$value
const _deepseek_ai_dsh_api_customizations_controller_customizations_balance_result$schema = () => (_deepseek_ai_dsh_api_customizations_controller_customizations_balance_result$schema$value ??= z.object({
  'state': z.union([z.literal("failed"), z.literal("ready"), z.literal("no-key")]).readonly(),
  'currency': z.string().readonly().optional(),
  'total': z.string().readonly().optional(),
  'granted': z.string().readonly().optional(),
  'toppedUp': z.string().readonly().optional(),
}))
let _deepseek_ai_dsh_api_customizations_controller_customizations_removeMcpServer_parameter_0$schema$value
const _deepseek_ai_dsh_api_customizations_controller_customizations_removeMcpServer_parameter_0$schema = () => (_deepseek_ai_dsh_api_customizations_controller_customizations_removeMcpServer_parameter_0$schema$value ??= z.string())
let _deepseek_ai_dsh_api_customizations_controller_customizations_removeMcpServer_result$schema$value
const _deepseek_ai_dsh_api_customizations_controller_customizations_removeMcpServer_result$schema = () => (_deepseek_ai_dsh_api_customizations_controller_customizations_removeMcpServer_result$schema$value ??= z.void())
let _deepseek_ai_dsh_api_customizations_controller_customizations_setManagedMcpServerEnabled_parameter_0$schema$value
const _deepseek_ai_dsh_api_customizations_controller_customizations_setManagedMcpServerEnabled_parameter_0$schema = () => (_deepseek_ai_dsh_api_customizations_controller_customizations_setManagedMcpServerEnabled_parameter_0$schema$value ??= z.string())
let _deepseek_ai_dsh_api_customizations_controller_customizations_setManagedMcpServerEnabled_parameter_1$schema$value
const _deepseek_ai_dsh_api_customizations_controller_customizations_setManagedMcpServerEnabled_parameter_1$schema = () => (_deepseek_ai_dsh_api_customizations_controller_customizations_setManagedMcpServerEnabled_parameter_1$schema$value ??= z.boolean())
let _deepseek_ai_dsh_api_customizations_controller_customizations_setManagedMcpServerEnabled_result$schema$value
const _deepseek_ai_dsh_api_customizations_controller_customizations_setManagedMcpServerEnabled_result$schema = () => (_deepseek_ai_dsh_api_customizations_controller_customizations_setManagedMcpServerEnabled_result$schema$value ??= z.void())
let _deepseek_ai_dsh_api_customizations_controller_customizations_snapshot_parameter_0$schema$value
const _deepseek_ai_dsh_api_customizations_controller_customizations_snapshot_parameter_0$schema = () => (_deepseek_ai_dsh_api_customizations_controller_customizations_snapshot_parameter_0$schema$value ??= z.union([z.undefined(), z.intersection(z.string(), z.unknown())]))
let _deepseek_ai_dsh_api_customizations_controller_customizations_snapshot_result$schema$value
const _deepseek_ai_dsh_api_customizations_controller_customizations_snapshot_result$schema = () => (_deepseek_ai_dsh_api_customizations_controller_customizations_snapshot_result$schema$value ??= z.object({
  'skillsAvailable': z.boolean().readonly(),
  'presets': z.array(z.string()).readonly(),
  'skills': z.array(z.object({
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'whenToUse': z.string().readonly().optional(),
  'path': z.string().readonly().optional(),
  'source': z.string().readonly(),
  'provider': z.string().readonly(),
  'modelInvocable': z.boolean().readonly(),
  'userInvocable': z.boolean().readonly(),
  'presets': z.array(z.string()).readonly(),
})).readonly(),
  'skillsTruncated': z.boolean().readonly(),
  'mcpServers': z.array(z.object({
  'entryId': z.string().readonly(),
  'serverName': z.string().readonly(),
  'transport': z.union([z.literal("stdio"), z.literal("streamable-http")]).readonly(),
  'target': z.string().readonly(),
  'enabled': z.boolean().readonly(),
  'fiberPhase': z.union([z.literal(null), z.literal("failed"), z.literal("pending"), z.literal("loading"), z.literal("active"), z.literal("unloading")]).readonly(),
  'tools': z.array(z.object({
  'name': z.string().readonly(),
  'description': z.string().readonly(),
})).readonly(),
  'manageable': z.boolean().readonly(),
  'origin': z.union([z.literal("profile"), z.literal("panel"), z.literal("project")]).readonly(),
  'managedId': z.string().readonly().optional(),
})).readonly(),
  'rules': z.array(z.object({
  'name': z.string().readonly(),
  'path': z.string().readonly(),
  'scope': z.union([z.literal("project"), z.literal("user")]).readonly(),
  'bytes': z.number().readonly(),
})).readonly(),
  'rulesTruncated': z.boolean().readonly(),
  'usage': z.object({
  'instructionBytes': z.number().readonly(),
  'catalogBytes': z.number().readonly(),
  'estimatedTokens': z.number().readonly(),
  'budgetTokens': z.number().readonly(),
}).readonly(),
}))

export const TYPERT = {
  package: '@deepseek-ai/dsh-customizations-panel',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-customizations-panel#customizations/addMcpServer',
      service: 'customizations',
      namespace: 'customizations',
      method: 'addMcpServer',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'server',
          wire: 'server',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-customizations-panel/types#ManagedMcpServer',
            create: _deepseek_ai_dsh_api_customizations_controller_customizations_addMcpServer_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-customizations-panel#customizations/addMcpServer:result',
        create: _deepseek_ai_dsh_api_customizations_controller_customizations_addMcpServer_result$schema,
      },
      sourceLocation: {"file":"packages/api/customizations-controller/src/index.ts","line":290,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-customizations-panel#customizations/balance',
      service: 'customizations',
      namespace: 'customizations',
      method: 'balance',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-customizations-panel/types#CustomizationBalance',
        create: _deepseek_ai_dsh_api_customizations_controller_customizations_balance_result$schema,
      },
      sourceLocation: {"file":"packages/api/customizations-controller/src/index.ts","line":341,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-customizations-panel#customizations/removeMcpServer',
      service: 'customizations',
      namespace: 'customizations',
      method: 'removeMcpServer',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-customizations-panel#customizations/removeMcpServer:id',
            create: _deepseek_ai_dsh_api_customizations_controller_customizations_removeMcpServer_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-customizations-panel#customizations/removeMcpServer:result',
        create: _deepseek_ai_dsh_api_customizations_controller_customizations_removeMcpServer_result$schema,
      },
      sourceLocation: {"file":"packages/api/customizations-controller/src/index.ts","line":310,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-customizations-panel#customizations/setManagedMcpServerEnabled',
      service: 'customizations',
      namespace: 'customizations',
      method: 'setManagedMcpServerEnabled',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-customizations-panel#customizations/setManagedMcpServerEnabled:id',
            create: _deepseek_ai_dsh_api_customizations_controller_customizations_setManagedMcpServerEnabled_parameter_0$schema,
          },
        },
        {
          name: 'enabled',
          wire: 'enabled',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-customizations-panel#customizations/setManagedMcpServerEnabled:enabled',
            create: _deepseek_ai_dsh_api_customizations_controller_customizations_setManagedMcpServerEnabled_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-customizations-panel#customizations/setManagedMcpServerEnabled:result',
        create: _deepseek_ai_dsh_api_customizations_controller_customizations_setManagedMcpServerEnabled_result$schema,
      },
      sourceLocation: {"file":"packages/api/customizations-controller/src/index.ts","line":324,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-customizations-panel#customizations/snapshot',
      service: 'customizations',
      namespace: 'customizations',
      method: 'snapshot',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'sessionId',
          wire: 'sessionId',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            create: _deepseek_ai_dsh_api_customizations_controller_customizations_snapshot_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-customizations-panel/types#CustomizationsSnapshot',
        create: _deepseek_ai_dsh_api_customizations_controller_customizations_snapshot_result$schema,
      },
      sourceLocation: {"file":"packages/api/customizations-controller/src/index.ts","line":385,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "Host Remote owner of the `customizations` namespace.",
        "summary": "Host Remote owner of the `customizations` namespace.",
        "tags": [],
        "jsDoc": "/** Host Remote owner of the `customizations` namespace. */",
        "key": "customizations",
        "exportName": "CustomizationsController",
        "members": [
          {
            "kind": "method",
            "name": "addMcpServer",
            "signature": "@Remote('addMcpServer') async addMcpServer(server: ManagedMcpServer): Promise<void>",
            "summary": "Add one panel-managed MCP server and mount its row immediately.",
            "jsDoc": "/**\n * Add one panel-managed MCP server and mount its row immediately.\n * @param server - the record to store and mount.\n * @returns nothing; the caller re-reads the snapshot.\n * @throws RemoteError when the record is invalid or cannot be written.\n */"
          },
          {
            "kind": "method",
            "name": "removeMcpServer",
            "signature": "@Remote('removeMcpServer') async removeMcpServer(id: string): Promise<void>",
            "summary": "Remove one panel-managed MCP server and unmount its row.",
            "jsDoc": "/**\n * Remove one panel-managed MCP server and unmount its row.\n * @param id - managed record id.\n * @returns nothing; a missing record is already in the asked-for state.\n * @throws RemoteError when the store cannot be written.\n */"
          },
          {
            "kind": "method",
            "name": "setManagedMcpServerEnabled",
            "signature": "@Remote('setManagedMcpServerEnabled') async setManagedMcpServerEnabled(id: string, enabled: boolean): Promise<void>",
            "summary": "Enable or disable one panel-managed MCP server without touching the profile.",
            "jsDoc": "/**\n * Enable or disable one panel-managed MCP server without touching the profile.\n * @param id - managed record id.\n * @param enabled - whether the panel should mount the row.\n * @returns nothing; the caller re-reads the snapshot.\n * @throws RemoteError when the record is unknown or the store cannot be written.\n */"
          },
          {
            "kind": "method",
            "name": "balance",
            "signature": "@Remote('balance') async balance(): Promise<CustomizationBalance>",
            "summary": "Read the DeepSeek platform balance for this deployment's API key.",
            "jsDoc": "/**\n * Read the DeepSeek platform balance for this deployment's API key.\n *\n * A deployment without a stored key answers `no-key`; a refused or unreachable\n * request answers `failed`. Neither is an error: the pane reports what it knows.\n * @returns the wallet figures, or the state that explains their absence.\n */"
          },
          {
            "kind": "method",
            "name": "snapshot",
            "signature": "@Remote('snapshot') async snapshot(sessionId?: SessionId): Promise<CustomizationsSnapshot>",
            "summary": "Read every Skill, MCP server, and instruction file one Session's workspace holds.",
            "jsDoc": "/**\n * Read every Skill, MCP server, and instruction file one Session's workspace holds.\n *\n * The read owns no Session, so it projects the workspace directory of the\n * Session identity a caller names: skills merge across the composed presets and\n * the global layer read under that directory, MCP rows come from the Loader\n * wherever they were declared, and instruction files are probed from that\n * Session's directory. Without a named Session — or for one whose header\n * records no directory — the read falls back to the first registered Workspace.\n * @param sessionId - Session whose workspace the project-scoped read follows.\n * @returns the merged catalog, the MCP rows, the instruction chain, and the estimate.\n */"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "CustomizationBalance",
            "declaration": "export interface CustomizationBalance {\n    readonly state: 'ready' | 'no-key' | 'failed';\n    readonly currency?: string;\n    readonly total?: string;\n    readonly granted?: string;\n    readonly toppedUp?: string;\n}"
          },
          {
            "name": "CustomizationMcpServer",
            "declaration": "export interface CustomizationMcpServer {\n    readonly entryId: string;\n    readonly serverName: string;\n    readonly transport: 'stdio' | 'streamable-http';\n    readonly target: string;\n    readonly enabled: boolean;\n    readonly fiberPhase: 'pending' | 'loading' | 'active' | 'failed' | 'unloading' | null;\n    readonly tools: readonly CustomizationMcpTool[];\n    readonly manageable: boolean;\n    readonly origin: 'profile' | 'panel' | 'project';\n    readonly managedId?: string;\n}"
          },
          {
            "name": "CustomizationMcpTool",
            "declaration": "export interface CustomizationMcpTool {\n    readonly name: string;\n    readonly description: string;\n}"
          },
          {
            "name": "CustomizationRuleFile",
            "declaration": "export interface CustomizationRuleFile {\n    readonly name: string;\n    readonly path: string;\n    readonly scope: CustomizationRuleScope;\n    readonly bytes: number;\n}"
          },
          {
            "name": "CustomizationRuleScope",
            "declaration": "export type CustomizationRuleScope = 'user' | 'project';"
          },
          {
            "name": "CustomizationSkill",
            "declaration": "export interface CustomizationSkill {\n    readonly name: string;\n    readonly description: string;\n    readonly whenToUse?: string;\n    readonly path?: string;\n    readonly source: CustomizationSkillSource;\n    readonly provider: string;\n    readonly modelInvocable: boolean;\n    readonly userInvocable: boolean;\n    readonly presets: readonly string[];\n}"
          },
          {
            "name": "CustomizationSkillSource",
            "declaration": "export type CustomizationSkillSource = string;"
          },
          {
            "name": "CustomizationsSnapshot",
            "declaration": "export interface CustomizationsSnapshot {\n    readonly skillsAvailable: boolean;\n    readonly presets: readonly string[];\n    readonly skills: readonly CustomizationSkill[];\n    readonly skillsTruncated: boolean;\n    readonly mcpServers: readonly CustomizationMcpServer[];\n    readonly rules: readonly CustomizationRuleFile[];\n    readonly rulesTruncated: boolean;\n    readonly usage: CustomizationUsage;\n}"
          },
          {
            "name": "CustomizationUsage",
            "declaration": "export interface CustomizationUsage {\n    readonly instructionBytes: number;\n    readonly catalogBytes: number;\n    readonly estimatedTokens: number;\n    readonly budgetTokens: number;\n}"
          },
          {
            "name": "ManagedMcpServer",
            "declaration": "export interface ManagedMcpServer {\n    readonly id: string;\n    readonly serverName: string;\n    readonly transport: 'stdio' | 'streamable-http';\n    readonly command?: string;\n    readonly args?: readonly string[];\n    readonly env?: Readonly<Record<string, string>>;\n    readonly cwd?: string;\n    readonly url?: string;\n    readonly headers?: Readonly<Record<string, string>>;\n    readonly enabled: boolean;\n}"
          },
          {
            "name": "SessionId",
            "declaration": "export type SessionId = Branded<'SessionId'>;"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
